[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["oakveil-update", "mods", "client"]

[package]
namespace = "zfolmt"
name = "Eclipse"
versionNumber = "1.3.8"
description = "Client UI for Bloodcraft!"
websiteUrl = "https://github.com/mfoltz/Eclipse"
containsNsfwContent = false
