[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["1-0-update", "mods", "client"]

[package]
namespace = "zfolmt"
name = "Eclipse"
versionNumber = "1.3.2"
description = "Client companion mod for Bloodcraft!"
websiteUrl = "https://github.com/mfoltz/Eclipse"
containsNsfwContent = false
